wandb_version: 1

entropy_loss_scale:
  value: 0
learning_epochs:
  value: 5
learning_rate:
  value: 0.0001
max_timesteps:
  value: 30000
mini_batches:
  value: 8
oob_reward:
  value: -80
policy_units_l1:
  value: 256
policy_units_l2:
  value: 64
policy_units_l3:
  value: 128
rew_scale_action_smoothness:
  value: -0.5
rew_scale_alive:
  value: 0.2
rew_scale_position_approach:
  value: 20
rew_scale_position_prec:
  value: 15
rew_scale_reg_ang_vel:
  value: -0.05
rew_scale_target_reached:
  value: 120
rew_scale_vel_mask_penalty:
  value: -0.6
rew_scale_yaw_error:
  value: -5
rew_scale_yaw_prec:
  value: 10
reward_exp_beta:
  value: 1
reward_exp_beta_prec:
  value: 2
reward_exp_beta_yaw_prec:
  value: 6
rollouts:
  value: 32
target_hold_time_s:
  value: 1.2
target_reach_threshold:
  value: 0.1
target_reach_yaw_threshold:
  value: 0.15
tilt_death_reward:
  value: -30
uniciclo_docking_factor:
  value: 4
