wandb_version: 1

approach_brake_dist:
  value: 0.6
max_timesteps:
  value: 200000
rew_scale_action_smoothness:
  value: -11
rew_scale_aggressive_cmd:
  value: -6
rew_scale_approach_brake:
  value: -15
rew_scale_reg_ang_vel_wz:
  value: -0.045
rew_scale_reverse_vx:
  value: -80
rew_scale_vy_penalty_uniciclo:
  value: -250
rew_scale_vy_real_penalty_uniciclo:
  value: -175
yaw_gate_dist_uniciclo:
  value: 0.22
