wandb_version: 1

approach_brake_dist:
  value: 0.4
max_timesteps:
  value: 200000
rew_scale_action_smoothness:
  value: -11
rew_scale_aggressive_cmd:
  value: -9
rew_scale_approach_brake:
  value: -20
rew_scale_reg_ang_vel_wz:
  value: -0.035
rew_scale_reverse_vx:
  value: -70
rew_scale_vy_penalty_uniciclo:
  value: -200
rew_scale_vy_real_penalty_uniciclo:
  value: -125
yaw_gate_dist_uniciclo:
  value: 0.18
