wandb_version: 1

discount_factor:
  value: 0.99
entropy_loss_scale:
  value: 0.01
lambda_:
  value: 0.95
learning_epochs:
  value: 8
learning_rate:
  value: 0.0005
max_timesteps:
  value: 300000
mini_batches:
  value: 8
oob_reward:
  value: -80
policy_units_l1:
  value: 256
policy_units_l2:
  value: 256
policy_units_l3:
  value: 32
ratio_clip:
  value: 0.1
rew_scale_action_smoothness:
  value: -0.1
rew_scale_alive:
  value: 0.1
rew_scale_position_approach:
  value: 20
rew_scale_position_prec:
  value: 15
rew_scale_reg_ang_vel:
  value: -0.01
rew_scale_target_reached:
  value: 120
rew_scale_vel_mask_penalty:
  value: -0.6
rew_scale_yaw_error:
  value: -5
rew_scale_yaw_prec:
  value: 2
reward_exp_beta:
  value: 2
reward_exp_beta_prec:
  value: 5
reward_exp_beta_yaw_prec:
  value: 4
rollouts:
  value: 32
target_hold_time_s:
  value: 1.2
target_reach_threshold:
  value: 0.15
target_reach_yaw_threshold:
  value: 0.2
tilt_death_reward:
  value: -80
value_loss_scale:
  value: 1
